CREATE TABLE TOMATO.GROUP_MSG_LOG
(
  CHATMSG   NVARCHAR2(1000),
  NICKNAME  VARCHAR2(30 BYTE),
  DAYS      VARCHAR2(40 BYTE),
  HOURS     VARCHAR2(40 BYTE)
)


TABLESPACE ts_TOMATO
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
